# Generated by Django 4.2.4 on 2023-09-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_section_video_teacherprofile_courseenrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
